default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: family_app_development

test:
  <<: *default
  database: family_app_test
  username: postgres
  password: password
  host: localhost

production:
  primary:
    <<: *default
    url: <%= ENV["postgresql://family_app_db_q20i_user:OCxPsrUCf5865HUjyQNBobigmIUuEybg@dpg-d950gp67r5hc73dshv0g-a/family_app_db_q20i"] %>